controller:
  image:
    allowPrivilegeEscalation: false
  containerPort:
    http: 9080
    https: 9443
  ingressClassResource:
    default: true
  podSecurityContext:
    fsGroup: 101
    supplementalGroups: [101]
    seccompProfile:
      type: RuntimeDefault
    runAsNonRoot: true
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      add:
      - NET_BIND_SERVICE
      drop:
      - ALL
    runAsUser: 101
    runAsGroup: 101
  extraArgs:
    http-port: 9080
    https-port: 9443
    default-ssl-certificate: ${tls_secret_namespace}/${tls_secret_name}
    # enable-ssl-passthrough: true
  service:
    loadBalancerIP: ${load_balancer_ip_address}
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-resource-group: ${load_balancer_ip_resource_group_name}
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
  admissionWebhooks:
    patch:
      securityContext:
        supplementalGroups: [2000]
        seccompProfile:
          type: RuntimeDefault
        runAsGroup: 2000 